### PR TITLE
Added new routes

### PR DESCRIPTION
**Pull request by prytoegrian**
Cf. #1 

Hi ! Following #1, I added some new routes. They are neither very useful nor interesting, but I hope they could entertain someone. Now, each `QuoteType` has a score and a uuid for sort and selection purpose.
I added : 
* `/one/{uuid}` 
* `/top`
* `/one/{uuid}/like`
* `/one/{uuid}/dislike`

The routes `/one/{uuid}/like` and `/one/{uuid}/dislike` don't follow ReST best practices since this principle forbid verbs in routes but I failed to find a way to represent what I wanted to build. If you have any idea, I'll take it with pleasure.

If, for a reason or another, you don't approve this PR, I won't mind. I really enjoyed play with your software and practice my golang.

Regards.

### CODE REVIEW

**Comment by bruno-chavez** [comment]
Hey I just tested this fork, this is really cool, thanks for the PR!

**Comment by prytoegrian** [comment]
You're welcome, thanks to you !

**Comment by prytoegrian** [comment]
Hum, I just saw you reverted the PR (I wanna use master to add some tests). Did you find any bugs in my code ?

**Comment by bruno-chavez** [comment]
I reverted the PR on master since I wanted to re-structure the project to better accommodate your changes, until then I made a separate branch with all your changes.

**Comment by bruno-chavez** [comment]
@prytoegrian just pushed to main all your changes, made some minor fixes, thanks for your time!

**Pull request merged**
