### PR TITLE
added Delete API, Will delete the quote permanently.

### PR DESCRIPTION
**Pull request by aneesh1992**
added Delete API, Will delete the quote permanently. Use wisely. Live well.

### CODE REVIEW

**Comment by aneesh1992** [comment]
can someone help me with the failed build? I have not modified the line it is failing. I was working on a windows machine

**Comment by bruno-chavez** [comment]
Looking at your fork, apparently you deleted an import path, check your latest commit, maybe that's it?

**Comment by aneesh1992** [comment]
@bruno-chavez How do I restart the build? The last build didn't execute and failed after 10 mins. Could you assist?

**Comment by bruno-chavez** [comment]
hi as you can see [here](https://github.com/bruno-chavez/restedancestor/pull/8/commits) every time you push a commit for the PR the build gets restarted so its still failing, looks like the import wasnt the problem after all, might have to do deeper debugging to see what the problem is

**Comment by bruno-chavez** [comment]
Hey since this PR is not compiling, I will close it for now, if you make it compile feel free to make another PR.

**Pull request closed without merging**
